[build]
  command = "pnpm run generate"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--shamefully-hoist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
